theme: minima
title: "gilang's blog"
description: "tempat sharing ide, kode, dan hasil ngulik-ngulik tech."
url: "https://gilangf3000.github.io"
author: "gilang"
keywords: [blog, gilang, tech, ngulik, tutorial, vps murah, rdp gratis, google cloud tutorial, cloudflare tunnel, belajar linux, sysadmin indonesia, gilangf3000, tutorial rdp, vpn vps, tunneling cloudflare, ssh vps, remote desktop, gcp tutorial, indonesia tech blog]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

twitter:
  username: gilangf3000
  card: summary_large_image
social:
  name: gilang
  links:
    - https://github.com/gilangf3000
logo: /assets/img/welcome.png

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag