theme: minima
title: "gilang's blog"
description: "tempat sharing ide, kode, dan hasil ngulik-ngulik tech."
url: "https://gilangf3000.github.io"
author: "gilang"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap